### ISSUE TITLE
tools.Writer class throws Exception

### ISSUE THREAD

**Issue by vinceecws** [kylejwolff/COVID-19-SPARK#38]
For machines running on winutils.exe Hadoop binaries, calling Writer.writeCSV will result in the following Exception:

![unknown](https://user-images.githubusercontent.com/19466657/129976258-077f7772-a4e1-41c5-acbe-0c3d54dd0136.png)

The same code has been tested on Mac OS X Catalina with the same dependencies on Hadoop 3.3.1, which runs fine.

**Comment by kylejwolff** [comment]
Found a solution to this here: https://stackoverflow.com/questions/41851066/exception-in-thread-main-java-lang-unsatisfiedlinkerror-org-apache-hadoop-io

1. download hadoop.dll from https://github.com/cdarlint/winutils
2. place hadoop.dll in the same directory as winutil.exe

**Comment by vinceecws** [comment]
Closed with @kylejwolff's solution

> Found a solution to this here: https://stackoverflow.com/questions/41851066/exception-in-thread-main-java-lang-unsatisfiedlinkerror-org-apache-hadoop-io
> 
> 1. download hadoop.dll from https://github.com/cdarlint/winutils
> 2. place hadoop.dll in the same directory as winutil.exe
